apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
<<<<<<< HEAD
  replicas: 2
=======
  replicas: 1
>>>>>>> parent of 916ce9d... change variable
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
